.github/workflows/broken_links_checker.yml, .github/workflows/interface-ci-build.yml, .gitignore, LICENSE, README.md, doc/changes/changelog.md, doc/changes/changes_0.1.0.md, interface/.gitignore, interface/package.json, interface/src/api.ts, interface/tsconfig.json
=> feature/1: Added extension interface

.github/workflows/render-design.yml, README.md, doc/changes/changes_0.1.0.md, doc/design/design.md
=> doc/4: Added design

doc/changes/changes_0.1.0.md, doc/design/design.md, extensionAPI/extensionApi.go, extensionAPI/extensionApi_test.go, extensionController/extensionController_test.go, generatedApiDocs/docs.go, generatedApiDocs/swagger.json, generatedApiDocs/swagger.yaml, integrationTesting/extensionForTesting/extensionForTestingTemplate.ts, integrationTesting/extensionForTesting/package.json, integrationTesting/testExtensionBuilder.go, restAPI/restApi.go, restAPI/restApi_test.go
=> feature/14: Added parameters to installations response

.github/workflows/broken_links_checker.yml, .github/workflows/ci-build.yml, .project-keeper.yml, dependencies.md, doc/changes/changes_0.1.0.md, extensionAPI/extensionApi.go, extensionAPI/extensionApi_test.go, extensionController/extensionController.go, extensionController/extensionController_test.go, generatedApiDocs/docs.go, generatedApiDocs/swagger.json, generatedApiDocs/swagger.yaml, go.mod, go.sum, integrationTesting/extensionForTesting/extensionForTestingTemplate.ts, restAPI/restApi.go, restAPI/restApi_test.go
=> #41: Add request for installing extensions

.gitignore, parameterValidator/.gitignore, parameterValidator/package.json, parameterValidator/parameterValidator.go, parameterValidator/parameterValidator.js, sonar-project.properties
Checking in generated code is required for running go install
=> Fix go install

backend/ExasolSqlClient.go, backend/ExasolSqlClient_test.go, extensionAPI/ExaMetadata.go, extensionAPI/context.go, extensionController/extensionController.go, integrationTesting/scriptFixtures.go, integrationTesting/testExtensionBuilder.go, restAPI/restApi.go
=> Minor refactorings

.gitignore, extensionAPI/ExaMetadata_test.go, extensionAPI/errorHandlingExtension.go, extensionAPI/errorHandlingExtension_test.go, extensionAPI/extensionApi.go, extensionAPI/extensionApi_test.go, extensionController/controller_i_test.go, extensionController/controller_test.go, integrationTesting/dbTestSetup.go, integrationTesting/extensionForTesting/extensionForTestingTemplate.ts, integrationTesting/extensionForTesting/package.json, integrationTesting/testExtensionBuilder.go, parameterValidator/parameterValidator_test.go
See https://github.com/exasol/extension-manager-interface/issues/27
=> Add tests for new TypeScript errors

backend/ExasolSqlClient_i_test.go, extensionAPI/errorHandlingExtension.go, extensionAPI/errorHandlingExtension_test.go, extensionAPI/extensionApi.go, extensionAPI/extensionApi_test.go, extensionController/controller.go, extensionController/controller_i_test.go, extensionController/controller_test.go, extensionController/mocks.go, extensionController/transactionController.go, extensionController/transactionController_test.go, integrationTesting/extensionForTesting/extensionForTestingTemplate.ts, integrationTesting/extensionForTesting/package.json, integrationTesting/testExtensionBuilder.go, parameterValidator/package-lock.json, parameterValidator/package.json, restAPI/mocks.go, restAPI/public.go, restAPI/requestUninstallExtension.go, restAPI/restApi_i_test.go, restAPI/restApi_test.go
=> #61 Uninstall an extension

.vscode/settings.json, doc/changes/changes_0.1.0.md, extensionAPI/errorHandlingExtension.go, extensionAPI/extensionApi_test.go, extensionController/controller.go, extensionController/controller_i_test.go, extensionController/controller_test.go, extensionController/mocks.go, extensionController/transactionController.go, extensionController/transactionController_test.go, restAPI/common.go, restAPI/mocks.go, restAPI/public.go, restAPI/requestCreateInstance.go, restAPI/requestDeleteInstance.go, restAPI/requestInstallExtension.go, restAPI/requestListInstalledExtensions.go, restAPI/requestListInstances.go, restAPI/requestTestUtil.go, restAPI/requestUninstallExtension.go, restAPI/restApi_i_test.go, restAPI/restApi_test.go
=> #66 Refactor urls

extensionAPI/errorHandlingExtension.go, extensionAPI/errorHandlingExtension_test.go, extensionAPI/extensionApi.go, extensionAPI/extensionApi_test.go, extensionController/controller.go, extensionController/controller_i_test.go, extensionController/controller_test.go, extensionController/mocks.go, extensionController/transactionController.go, integrationTesting/extensionForTesting/extensionForTestingTemplate.ts, integrationTesting/extensionForTesting/package.json, integrationTesting/testExtensionBuilder.go, parameterValidator/parameterValidator.go, parameterValidator/parameterValidator_test.go, restAPI/dbConnection.go, restAPI/mocks.go, restAPI/public.go, restAPI/requestGetExtensionDetails.go, restAPI/requestListAvailableExtensions.go, restAPI/requestListInstalledExtensions.go, restAPI/requestTestUtil.go, restAPI/restApi_i_test.go, restAPI/restApi_test.go
=> #67: Remove InstanceParameters from findInstallations, add flags to installable versions

apiErrors/errors.go, apiErrors/errors_test.go, backend/ExasolSqlClient.go, doc/changes/changes_0.1.0.md, extensionAPI/extensionApi.go, extensionAPI/extensionApi_test.go, extensionController/transactionController.go, restAPI/requestResponseHelper.go, restAPI/restApi_i_test.go
=> #70 Return status 404 for unknown extension id

.project-keeper.yml, doc/changes/changelog.md, doc/changes/changes_0.1.1.md, extension-manager-integration-test-java/src/main/java/com/exasol/extensionmanager/itest/installer/InstallerFromGitHub.java, extensionAPI/errorHandlingExtension_test.go, extensionAPI/extensionApi.go, extensionAPI/extensionApi_test.go, pom.xml
=> #80 Add prefix to JS log messages

dependencies.md, doc/changes/changes_0.4.0.md, extension-manager-integration-test-java/pom.xml, extension-manager-integration-test-java/src/main/java/com/exasol/extensionmanager/itest/ExtensionTestConfig.java, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/itest/VersionConsistencyTest.java
=> #77: Use same EM version as the test library

doc/changes/changes_0.4.0.md, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/itest/ExasolMetadataIT.java, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/itest/ExtensionManagerClientIT.java, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/itest/ExtensionManagerSetupIT.java, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/itest/IntegrationTestCommon.java, pkg/extensionAPI/ExaMetadata.go
=> #107: Adapt metadata query to Exasol 8

.project-keeper.yml, cmd/main.go, doc/changes/changelog.md, doc/changes/changes_0.5.0.md, pkg/extensionAPI/context.go, pkg/extensionAPI/extensionApi_test.go, pkg/extensionController/BucketFsApi.go, pkg/extensionController/BucketFsApi_test.go, pkg/extensionController/controller.go, pkg/extensionController/list_files_recursively_udf.py, pkg/extensionController/mocks.go, pkg/extensionController/transactionController.go, pkg/extensionController/transactionController_test.go, pkg/restAPI/public.go, pom.xml
This is part of #116. More PR will be added later.
=> #116 Make BucketFS base path configurable

doc/changes/changes_0.5.0.md, doc/design.md, doc/system_requirements.md
=> #101 Add requirements

doc/changes/changes_0.5.0.md, doc/design.md, doc/system_requirements.md, extension-manager-client-java/pom.xml, extension-manager-integration-test-java/pom.xml, extension-manager-integration-test-java/src/main/java/com/exasol/extensionmanager/itest/ExtensionManagerClient.java, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/itest/ExtensionManagerClientIT.java, extension-manager-integration-test-java/testing-extension/package-lock.json, extension-manager-integration-test-java/testing-extension/package.json, extension-manager-integration-test-java/testing-extension/src/extension.ts, pkg/extensionAPI/errorHandlingExtension.go, pkg/extensionAPI/errorHandlingExtension_test.go, pkg/extensionAPI/extensionApi.go, pkg/extensionController/controller.go, pkg/extensionController/controller_i_test.go, pkg/extensionController/controller_mock.go, pkg/extensionController/controller_test.go, pkg/extensionController/transactionController.go, pkg/extensionController/transactionController_test.go, pkg/integrationTesting/extensionForTesting/extensionForTestingTemplate.ts, pkg/integrationTesting/extensionForTesting/package.json, pkg/integrationTesting/testExtensionBuilder.go, pkg/parameterValidator/package-lock.json, pkg/parameterValidator/package.json, pkg/restAPI/mocks.go, pkg/restAPI/public.go, pkg/restAPI/requestUpgradeExtension.go, pkg/restAPI/restApi_i_test.go, pkg/restAPI/restApi_test.go
=> #101 Add upgrade function

doc/design.md, pkg/backend/ExasolSqlClient.go, pkg/backend/ExasolSqlClient_i_test.go, pkg/backend/ExasolSqlClient_mock.go, pkg/backend/ExasolSqlClient_test.go, pkg/extensionAPI/context/context.go, pkg/extensionAPI/context/context_test.go, pkg/extensionAPI/errorHandlingExtension_test.go, pkg/extensionAPI/extensionApi_test.go, pkg/extensionController/bfs/BucketFsApi.go, pkg/extensionController/controller_i_test.go
Part of #101
This adds requirements for extension context and refactors the Simple SQL Client
=> #101 Add requirements for extension context

doc/changes/changes_0.5.1.md, extension-manager-integration-test-java/src/main/java/com/exasol/extensionmanager/itest/PreviousExtensionVersion.java, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/itest/PreviousExtensionVersionTest.java, pkg/restAPI/dbConnection.go
=> #134: Make adapter file optional for `PreviousExtensionVersion`

.github/workflows/ci-build.yml, .project-keeper.yml, dependencies.md, doc/changes/changelog.md, doc/changes/changes_0.5.3.md, go.mod, go.sum, pkg/backend/ExasolSqlClient_test.go, pkg/extensionAPI/context/bucketfs.go, pkg/extensionAPI/context/bucketfs_mock.go, pkg/extensionAPI/context/context.go, pkg/extensionAPI/context/context_test.go, pkg/extensionAPI/errorHandlingExtension_test.go, pkg/extensionAPI/extensionApi_test.go, pkg/extensionController/bfs/BucketFsApi.go, pkg/extensionController/bfs/BucketFsApi_i_test.go, pkg/extensionController/bfs/BucketFsApi_mock.go, pkg/extensionController/bfs/BucketFsApi_test.go, pkg/extensionController/bfs/list_files_recursively_udf.py, pkg/extensionController/controller.go, pkg/extensionController/controller_test.go, pkg/extensionController/transaction/transactionContext.go, pkg/extensionController/transaction/transactionContext_test.go, pkg/extensionController/transaction/transactionStarter_mock.go, pkg/extensionController/transactionController.go, pkg/extensionController/transactionController_test.go, pkg/integrationTesting/dbTestSetup.go, pkg/restAPI/dbConnection_test.go, pom.xml
=> #147 Refactoring: prepare BucketFS speedup

.github/workflows/ci-build.yml, .github/workflows/release_droid_prepare_original_checksum.yml, .project-keeper.yml, README.md, dependencies.md, doc/changes/changelog.md, doc/changes/changes_0.5.4.md, doc/developer_guide.md, doc/embedding_extension_manager.md, doc/extension_developer_guide.md, extension-manager-integration-test-java/src/main/java/com/exasol/extensionmanager/itest/ExasolMetadata.java, extension-manager-integration-test-java/src/main/java/com/exasol/extensionmanager/itest/ExasolVersionCheck.java, extension-manager-integration-test-java/src/main/java/com/exasol/extensionmanager/itest/ExtensionManagerSetup.java, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/ExampleIT.java, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/itest/ExasolVersionCheckIT.java, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/itest/ExasolVersionCheckTest.java, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/itest/ExtensionManagerSetupTest.java, extension-manager-integration-test-java/src/test/java/com/exasol/extensionmanager/itest/IntegrationTestCommon.java, go.mod, go.sum, pkg/extensionAPI/exaMetadata/ExaMetadata.go, pkg/extensionAPI/exaMetadata/ExaMetadata_test.go, pkg/integrationTesting/dbTestSetup.go, pom.xml
=> #152 Migrate to Exasol 8

.gitignore, doc/changes/changes_0.5.5.md, pkg/extensionAPI/errorHandlingExtension.go, pkg/extensionAPI/errorHandlingExtension_test.go, pkg/extensionController/controller.go, pkg/extensionController/controller_test.go, pkg/integrationTesting/extensionForTesting/extensionForTestingTemplate.js
=> #155: Check if instances are supported before listing them
